const Types = {
    ADD_NEW_FOLDER: "ADD_NEW_FOLDER",
    DELETE_ALL_ITEMS:"DELETE_ALL_ITEMS",
    ADD_NEW_DOC:"ADD_NEW_DOC",
    DELETE_ITEM:"DELETE_ITEM",
    ADD_TRASH:"ADD_TRASH",
    DELETE_TRASH:"DELETE_TRASH",
    DELETE_TRASH_ITEM:"DELETE_TRASH_ITEM",
    RESTORE_TRASH_ITEM:"RESTORE_TRASH_ITEM",
    ADD_DOC_TEXT:"ADD_DOC_TEXT"
}

export default Types